### ISSUE TITLE
tab.gnome_terminal not found

### ISSUE THREAD

**Issue by mike-czarnota** [oh-my-fish/plugin-tab#12]
Hello,
I've pasted the snippet into `~/.config/fish/functions/tab.fish` and when running `tab` i get this error:
```tab.gnome_terminal: command not found
~/.config/fish/functions/tab.fish (line 78):       tab.gnome_terminal "$cdto" "$cmd"
                                                   ^
in function “tab”
	called on standard input
```
I was looking for the solution, but found nothing.

EDIT:
I didn't notice it's an `omf` plugin... Just found the snippet from Google...
My bad

**Comment by bobthecow** [comment]
No worries! If you want to use them without omf, you can copy all the files to your `functions` directory.
