### ISSUE TITLE
Add support for Terminology

### ISSUE THREAD

**Issue by timofonic** [oh-my-fish/plugin-tab#13]
Hello.

Can you please add support for Terminology?

```
 ~  tab
test returned eval errors:
        invalid integer ''
Unknown terminal:
```

Thanks in advance.

**Comment by bobthecow** [comment]
I would love for this to support Terminology. Unfortunately I don't use it, and couldn't find any info about scriptability for this sort of thing in any of the documentation or source code. Feel free to reopen if I missed something, or even better, contribute a pull request to add it!
