### ISSUE TITLE
Tab not opened in iTerm

### ISSUE THREAD

**Issue by dan-c-underwood** [oh-my-fish/plugin-tab#2]
Running `tab` (or with any options) does not open a new tab and instead causes an error code to be returned.

iTerm2 Build: 2.9.20150830
Fish Version: 2.2.0

**Comment by bobthecow** [comment]
See [the install instructions in the readme](https://github.com/oh-my-fish/plugin-tab#install). You likely need to tell it your default session profile name.

**Comment by dan-c-underwood** [comment]
Both it and the value of `tab_iterm_profile` are set to "Default" with the same result.

**Comment by bpinto** [comment]
If you remove the `2>/dev/null` from the [code](https://github.com/oh-my-fish/plugin-tab/blob/master/tab.fish#L45), you might have a more helpful error.

**Comment by dan-c-underwood** [comment]
The reported error is:

```
53:61: syntax error: Expected end of line but found identifier. (-2741)
```

The location doesn't seem to match up to lines in `tab.fish` however since the same error message appears if you run the AppleScript directly in the terminal.

**Comment by bobthecow** [comment]
You might have better error messages if you run the AppleScript source in Script Editor. Give that a shot?

**Comment by dan-c-underwood** [comment]
Looks like the issue is with the line (47):

```
tell current terminal
```

It doesn't seem to like the `terminal` part! The error message within Script Editor is the same however.

**Comment by dan-c-underwood** [comment]
The issue may be related to the following: https://iterm2.com/applescript.html

**Comment by bobthecow** [comment]
Got it. I won't get to it for a couple of days. If you want to come up with a fix I'd appreciate a PR :)

**Comment by dan-c-underwood** [comment]
I'll give it a bash :)

**Comment by dan-c-underwood** [comment]
(Or should that be "Give it a fish")?
