### ISSUE TITLE
Add support for the KDE terminal, Konsole

### ISSUE THREAD

**Issue by severen** [oh-my-fish/plugin-tab#5]
The command for opening a new tab in a running Konsole session is: `konsole --new-tab`.

`konsole --new-tab -e <command>` will open a new tab and run the specified command.

**Comment by bobthecow** [comment]
Nice! I don't have a KDE machine handy to test on. Do you want to take a shot at a pull request? It should be as simple as adding:

```
case 'Konsole' # or whatever konsole reports `$TERM_PROGRAM` as
  konsole --new-tab -e "cd \"$cdto\"$cmd"
```

… around line 90 (just before the `case '*'`).

**Comment by severen** [comment]
I'll give it a crack once I get home, I'm pretty sure most Linux terminal
emulators don't export `$TERM_PROGRAM` though so detection may be a bit
tricky.

**Comment by bobthecow** [comment]
@SShrike any update on this?

**Comment by severen** [comment]
I've confirmed so far that Konsole doesn't export `$TERM_PROGRAM` so that detection method is off the table.

I'm not quite sure how we could handle detection other than by requiring Konsole users to manually set `$TERM_PROGRAM` to `konsole` manually.

I could create an issue on the upstream Konsole repository for `$TERM_PROGRAM` support but I doubt they'd accept the proposition.

**Comment by bobthecow** [comment]
how about `$KONSOLE_DBUS_SERVICE` or `$KONSOLE_DBUS_SESSION`?

**Comment by bobthecow** [comment]
I just added a `konsole-support` branch, which should work assuming I've guessed everything correctly. I don't have a KDE box to test on, so if you could give it a shot, that'd be rad :)

https://github.com/oh-my-fish/plugin-tab/tree/konsole-support

**Comment by bobthecow** [comment]
Konsole support has landed in master. Let me know if you have any issues with it!
