### ISSUE TITLE
Add support for splitting iTerm tabs horizontally

### ISSUE THREAD

**Issue by JaceHensley** [oh-my-fish/plugin-tab#6]
Using `tab -s` splits the tab vertically I would expect another command that would split it horizontally maybe something like `tab --split-vertically` with a shorthand of `tab -s-v`

**Comment by bobthecow** [comment]
In iTerm's opinion, the current split is "vertically". We could definitely add a "split horizontally", but my preferred argument for that (`-h`) is already taken for "help". Mebbe `-H`?

`-S` might be my favorite alternative. Using shift to change from vertical to horizontal is somewhat analogous to the current split (`cmd+d`) / split horizontally (`cmd+shift+d`). I'm going to push a change with support for that for now, and we can re-address if that's not quite right :)

**Comment by JaceHensley** [comment]
Works for me, thanks for the quick response!

**Comment by bobthecow** [comment]
No problem!
